IF
	Global("VP_Guild_Attacked","GLOBAL",1)
	Global("ETG2Dave","AR0300",0)
THEN
	RESPONSE #100
		TriggerActivation("Tran0305",FALSE)
		TriggerActivation("Tran0306",FALSE)
		TriggerActivation("Tran0327",TRUE)
		TriggerActivation("Tran0328",TRUE)
		TriggerActivation("Tran0329",TRUE)
		TriggerActivation("Tran0307a",FALSE)
		TriggerActivation("Tran0307b",FALSE)
		TriggerActivation("Info307a",TRUE)
		TriggerActivation("Info307b",TRUE)
		SetGlobal("ETG2Dave","AR0300",1)
END

