IF
	Global("VP_Improved_Area_Items","MYAREA",0)
THEN
	RESPONSE #100
		SetGlobal("VP_Improved_Area_Items","MYAREA",1)
		ActionOverride("Chest1",CreateItem("SCRL09",0,0,0))  // Protection From Undead
		ActionOverride("Chest1",CreateItem("SCRL7O",0,0,0))  // Protection From Magical Weapons
		ActionOverride("Chest3",CreateItem("SCRL9R",0,0,0))  // Time Stop
		ActionOverride("Chest4",CreateItem("AROW06",20,0,0))  // Arrow of Detonation
		ActionOverride("Chest5",CreateItem("SCRL9T",0,0,0))  // Meteor Swarm
		ActionOverride("Chest5",CreateItem("BULL04",100,0,0))  // Sunstone Bullet +1
		ActionOverride("Chest5",CreateItem("MISC45",0,0,0))  // Rogue Stone
		ActionOverride("Drawer1",CreateItem("SCRL8F",0,0,0))  // Project Image
		ActionOverride("Drawer1",CreateItem("SCRL9M",0,0,0))  // Spellstrike
		ActionOverride("Drawer1",CreateItem("HELM19",0,0,0))  // Dusty Rose Ioun Stone
		ActionOverride("Drawer1",CreateItem("AROW15",80,0,0))  // Arrow +3
		ActionOverride("Chest6",CreateItem("COFFEE",5,0,0))
		ActionOverride("Chest6",CreateItem("NEOLIT",0,0,0))
END