IF
	Global("vpEnhancedArea","MYAREA",0)
THEN
	RESPONSE #100
		SetGlobal("vpEnhancedArea","MYAREA",1)
		ActionOverride("hobsha01",DestroySelf())
		CreateCreature("vpmack",[1385.640],6)
		CreateCreature("vplincol",[1339.696],6)
		CreateCreature("vpcoulso",[1370.673],6)
		CreateCreature("vpskye",[1375.723],6)
		CreateCreature("vpmay",[1417.677],6)
		CreateCreature("vpfitz",[1459.700],6)
		CreateCreature("vpsimmon",[1418.720],6)
END