//Creature files

ACTION_FOR_EACH anomen IN anomen6 anomen7 anomen8 anomen9 anomen10 anomen12 BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%anomen%.cre~ THEN BEGIN
		COPY_EXISTING ~%anomen%.cre~ ~override~
            WRITE_SHORT 0x46 8
            WRITE_SHORT 0x48 8
            WRITE_BYTE 0x52 12
            WRITE_BYTE 0x53 2
            WRITE_BYTE 0x239 72 // Ex. STR
            WRITE_BYTE 0x23a 14 // INT
            WRITE_BYTE 0x23c 18 // DEX
            WRITE_BYTE 0x23d 18 // CON